services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_Password=Senha@123
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
